[project]
name = "remem"
version = "0.1.0"
description = "A simple tool to chunk, embed, and recall memory — from diaries to chat logs."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'
